[package]
name = "users"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
mikrotik-rs = {package = "mikrotik-rs",  path = "../../mikrotik-rs" }
tokio = { version = "1.36.0", features = ["full"] }

[lints]
workspace = true
